[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "slidemodel"
version = "0.0.1"
requires-python = ">=3.9"

[tool.pytest.ini_options]
pythonpath = ["src"]
